### PR TITLE
Initial authentication support

### PR DESCRIPTION
**Pull request by patrickod**
These commits add initial authentication support. The 1st request on a given connection will fail as the authentication callbacks have not had time to fully execute. All requests on that connection thereafter however will work.

### CODE REVIEW

**Comment by patrickod** [comment]
Just realised this includes unnecessary changes to the README. I'm not sure if you can select which commits from this pull request to accept. If it's a problem I can close this and open a fresh pull request

**Comment by jehiah** [comment]
hey @patrickod, i worked out a version of this change that handles authentication seamlessly on every connection; would you be able to check it out from my fork and test that? da7fc2895407c8880f8b7128cd5f4e52bcda928a

**Comment by patrickod** [comment]
hey, so I just played around with this and a simple tornado app to try and benchmark this. (gist is here: https://gist.github.com/524eb989f350d0c1a5a2). I've been running benchmarks with palb, a python implementation of apache's ab tool. 

I've been running 1000 request batches with variable amounts of concurrent connections. It seems that when the number of concurrent connections is greater than the max_cached variable requests start failing with various errors. Here's a gist of the errors thrown when running 100 requests over 10 connections. https://gist.github.com/2e3110e316c41423de50 

It seems that connections are accidentally being shared and thus failing.

**Comment by jehiah** [comment]
thanks @patrickod. i committed that test code as c6923c11a8e8c8bcbd36e7f03659a691c0d039a1 and found/fixed the issue where the connection got added to the pool prematurely c59aa27a36aa61da937535c370d22a72fa4956ac. can you re-test that code passes for me now?

**Comment by patrickod** [comment]
It seems that this fixes the authentication problem. The only time the test script fails is when the amount of concurrent connections is greater than the maximum amount of Mongo connections in the pool, which is perfectly reasonable behavior

**Pull request closed without merging**
