### PR TITLE
Non-Blocking Connection and Timeout Support

### PR DESCRIPTION
**Pull request by bufferx**
**Issue**
The Blocking IO Connection will causing that the tornado service can not respond new HTTP Request,  when MongoDB server goes down(Error: no route to host). 

**New Feature**
create Non-blocking connection to mongodb service, support for connection timeout and request timeout, when using tornado as the Async Backend

### CODE REVIEW

**Comment by jehiah** [comment]
@bufferx thanks for working on this. Can you rebase on bitly/master? some things have recently been added that conflict with this change set.

**Comment by bufferx** [comment]
@jehiah I have rebase and re-pull-request right [here](https://github.com/bitly/asyncmongo/pull/61). please check it, thanks.

**Comment by jehiah** [comment]
Thanks for rebasing this @bufferx. I will take a look at the new pull request you opened and give comments on the code there.

FYI: there is no need to re-open new pull requests when making updates. Pull requests are designed to reflect the current state of a branch, so it's expected for you to push up new requests and change that branch during a code review before it get's merged. The general process we follow at bitly is to rebase and squash down to a single commit at the end of development before code is merged, but not before so it's easy to see changes as it's being worked on.

**Comment by bufferx** [comment]
@jehiah thanks for your suggestion. I'm so sorry that I'm not familiar with the use of GitHub system.

**Pull request closed without merging**
